steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/ml-sales-repo-arnab-ghosh/cloud-run-app:$SHORT_SHA",
        ".",
      ]
    id: "Build Docker image"

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/ml-sales-repo-arnab-ghosh/cloud-run-app:$SHORT_SHA",
      ]
    id: "Push to Artifact Registry"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud deploy releases create release-$BUILD_ID \
          --delivery-pipeline=cloud-run-arnab-ghosh-ml-sales-pipeline \
          --region=${_REGION} \
          --images=app=${_REGION}-docker.pkg.dev/$PROJECT_ID/ml-sales-repo-arnab-ghosh/cloud-run-app:$SHORT_SHA \
          --skaffold-file=skaffold.yaml \
          --render-strategy=skaffold-native
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
# substitutions:
#   _SERVICE_NAME: cloud-run-app
