steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/ml-sales-repo-arnab-ghosh/cloud-run-app:$SHORT_SHA",
        ".",
      ]
    id: "Build Docker image"

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/ml-sales-repo-arnab-ghosh/cloud-run-app:$SHORT_SHA",
      ]
    id: "Push to Artifact Registry"

  # Step 3: Generate service.yaml from template
  - name: "bash"
    entrypoint: "bash"
    args:
      - -c
      - |
        envsubst < service.yaml.template > service.yaml
    env:
      - SHORT_SHA=$SHORT_SHA

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "deploy",
        "releases",
        "create",
        "release-$BUILD_ID",
        "--delivery-pipeline",
        "cloud-run-arnab-ghosh-ml-sales-pipeline",
        "--region",
        "${_REGION}",
        "--images",
        "ml-sales-app-arnab-ghosh-image=${_REGION}-docker.pkg.dev/$PROJECT_ID/ml-sales-repo-arnab-ghosh/cloud-run-app:$SHORT_SHA",
      ]
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
