steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/ml-sales-repo-arnab-ghosh/cloud-run-app:$SHORT_SHA",
        ".",
      ]
    id: "Build Docker image"

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/ml-sales-repo-arnab-ghosh/cloud-run-app:$SHORT_SHA",
      ]
    id: "Push to Artifact Registry"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    env:
      - "RELEASE_TIMESTAMP=$(date '+%Y%m%d-%H%M%S')"
    args:
      - -c
      - |
        gcloud deploy releases create release-$RELEASE_TIMESTAMP \
          --delivery-pipeline cloud-run-arnab-ghosh-ml-sales-pipeline \
          --region us-central1 \
          --images app=us-central1-docker.pkg.dev/$PROJECT_ID/ml-sales-repo-arnab-ghosh/cloud-run-app:$SHORT_SHA \
          --skaffold-file skaffold.yaml

  # - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  #   entrypoint: "gcloud"
  #   args:
  #     [
  #       "run",
  #       "deploy",
  #       "ml-sales-service-cloud-run-arnab-ghosh",
  #       "--image",
  #       "us-central1-docker.pkg.dev/$PROJECT_ID/ml-sales-repo-arnab-ghosh/cloud-run-app:$SHORT_SHA",
  #       "--region",
  #       "us-central1",
  #       "--platform",
  #       "managed",
  #       "--allow-unauthenticated",
  #       "--set-env-vars",
  #       "VERSION=$SHORT_SHA",
  #     ]
  #   id: "Deploy to Cloud Run"

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _SERVICE_NAME: cloud-run-app
