apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: ml-sales-service-cloud-run-arnab-ghosh

profiles:
  - name: dev
    manifests:
      rawYaml:
        - deploy-dev.yaml

deploy:
  cloudrun: {}
