apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: ml-sales-service-cloud-run-arnab-ghosh

profiles:
  - name: dev
    manifests:
      rawYaml:
        - deploy-dev.yaml

deploy:
  cloudrun: {}

verify:
  - name: health-check
    container:
      image: gcr.io/cloud-builders/curl
      command: ["curl"]
      args:
        [
          "-f",
          "https://ml-sales-service-cloud-run-arnab-ghosh-954297282737.us-central1.run.app",
        ]
